[package]
name = "meili-crates"
version = "0.1.0"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.6"
flate2 = "1.0.11"
futures-preview = "0.3.0-alpha.14"
runtime = "0.3.0-alpha.7"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
surf = "1.0.2"
tar = "0.4.26"
walkdir = "2.0"
